### ISSUE TITLE
Update hardcoded Nodejs14 runtime

### ISSUE THREAD

**Issue by mikejgray** [wheatstalk/cdk-intrinsic-validator#763]
In the [alarm-monitor code](https://github.com/wheatstalk/cdk-intrinsic-validator/blob/ac86d962daa17653318c70f74cc624e3b66a0771/src/alarm-monitor.ts#L48), possibly in other places, the Lambda runtime is hardcoded to NodeJS 14. This is causing deployment failures because that runtime is no longer supported in AWS.

At a minimum the Node version should move to a supported version, and it would also be nice to be able to override that value via a property somewhere.

**Comment by misterjoshua** [comment]
Sounds good. I'll check out your PR.
