### ISSUE TITLE
Support for CDK v2 would be nice :-)

### ISSUE THREAD

**Issue by jabalsad** [wheatstalk/cdk-intrinsic-validator#98]
Hello!

Support for CDK v2 would be nice! I might try and see if I can get this working in a fork, but it's unclear how I will actually be able to publish/consume the npm package from a forked repository.

**Comment by jabalsad** [comment]
Would you want to support both CDK versions? CDK v1 is deprecated at this point so I think it makes sense to bump the version number and just support CDKv2 going forward.

**Comment by misterjoshua** [comment]
> Would you want to support both CDK versions? CDK v1 is deprecated at this point so I think it makes sense to bump the version number and just support CDKv2 going forward.

I want to resolve the last of the issues you spotted impacting v1 before we break to v2, then yeah, it makes sense to bump the version and support just v2 going forward.

**Comment by misterjoshua** [comment]
> > I want to resolve the last of the issues you spotted impacting v1 before we break to v2, then yeah, it makes sense to bump the version and support just v2 going forward.
> 
> I don't think that would be easy without digging into CDK. It appears that the isComplete handler raises some kind of error when the lambda function returns `{ IsComplete: false }`. However, when it returns true, then the provider framework continues as normal.

Ah, I see. Yes, actually this is expected. Their waiter state machine handles `{ IsComplete: false }` with lambda retries, expecting the lambda to throw an exception while `IsComplete` is false.

See: https://github.com/aws/aws-cdk/blob/4dbb2460d658fc8f734773545be6b47ebebaea5c/packages/%40aws-cdk/custom-resources/lib/provider-framework/runtime/framework.ts#L71

I think we should be able to merge v2 now.
